import IISLaboratornaya_rabota_Stacionar_2ПациентEController from '../i-i-s-laboratornaya-rabota-stacionar-2-пациент-e';

var IISLaboratornaya_rabota_Stacionar_2ПациентENewController = IISLaboratornaya_rabota_Stacionar_2ПациентEController;
export default IISLaboratornaya_rabota_Stacionar_2ПациентENewController;
