import IISLaboratornaya_rabota_Stacionar_2ИтОтчПоЛетEController from '../i-i-s-laboratornaya-rabota-stacionar-2-ит-отч-по-лет-e';

var IISLaboratornaya_rabota_Stacionar_2ИтОтчПоЛетENewController = IISLaboratornaya_rabota_Stacionar_2ИтОтчПоЛетEController;
export default IISLaboratornaya_rabota_Stacionar_2ИтОтчПоЛетENewController;
