import IISLaboratornaya_rabota_Stacionar_2ОтПоОцЛечПацEController from '../i-i-s-laboratornaya-rabota-stacionar-2-от-по-оц-леч-пац-e';

var IISLaboratornaya_rabota_Stacionar_2ОтПоОцЛечПацENewController = IISLaboratornaya_rabota_Stacionar_2ОтПоОцЛечПацEController;
export default IISLaboratornaya_rabota_Stacionar_2ОтПоОцЛечПацENewController;
