//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laboratornaya_rabota_Stacionar_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Диагноз.
    /// </summary>
    // *** Start programmer edit section *** (Диагноз CustomAttributes)

    // *** End programmer edit section *** (Диагноз CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДиагнозE", new string[] {
            "Наименование as \'Диагноз\'"})]
    [View("ДиагнозL", new string[] {
            "Наименование as \'Диагноз\'"})]
    public class Диагноз : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Диагноз CustomMembers)

        // *** End programmer edit section *** (Диагноз CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Диагноз.Наименование CustomAttributes)

        // *** End programmer edit section *** (Диагноз.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Диагноз.Наименование Get start)

                // *** End programmer edit section *** (Диагноз.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Диагноз.Наименование Get end)

                // *** End programmer edit section *** (Диагноз.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Диагноз.Наименование Set start)

                // *** End programmer edit section *** (Диагноз.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Диагноз.Наименование Set end)

                // *** End programmer edit section *** (Диагноз.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДиагнозE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДиагнозE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДиагнозE", typeof(IIS.Laboratornaya_rabota_Stacionar_2.Диагноз));
                }
            }
            
            /// <summary>
            /// "ДиагнозL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДиагнозL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДиагнозL", typeof(IIS.Laboratornaya_rabota_Stacionar_2.Диагноз));
                }
            }
        }
    }
}
