//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laboratornaya_rabota_Stacionar_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ит отч по лет.
    /// </summary>
    // *** Start programmer edit section *** (ИтОтчПоЛет CustomAttributes)

    // *** End programmer edit section *** (ИтОтчПоЛет CustomAttributes)
    [AutoAltered()]
    [Caption("Ит отч по лет")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИтОтчПоЛетE", new string[] {
            "Дата as \'Дата cоздания\'",
            "СпрСотр as \'Фио сотрудника\'",
            "СпрСотр.Фио as \'Фио сотрудника\'",
            "ПериодОт as \'Период От\'",
            "ПериодДо as \'Период До\'",
            "Место as \'Место\'"})]
    [AssociatedDetailViewAttribute("ИтОтчПоЛетE", "ТЧИтОтчПоЛет", "ТЧИтОтчПоЛетE", true, "", "Табличная часть Итоговый отчет по летальности", true, new string[] {
            ""})]
    [View("ИтОтчПоЛетL", new string[] {
            "Дата as \'Дата создания\'",
            "СпрСотр.Фио as \'Фио сотурдника\'",
            "ПериодОт as \'Период От\'",
            "ПериодДо as \'Период До\'",
            "Место as \'Место\'"})]
    public class ИтОтчПоЛет : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private System.DateTime fПериодОт;
        
        private System.DateTime fПериодДо;
        
        private string fМесто;
        
        private IIS.Laboratornaya_rabota_Stacionar_2.СпрСотр fСпрСотр;
        
        private IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТЧИтОтчПоЛет fТЧИтОтчПоЛет;
        
        // *** Start programmer edit section *** (ИтОтчПоЛет CustomMembers)

        // *** End programmer edit section *** (ИтОтчПоЛет CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ИтОтчПоЛет.Дата CustomAttributes)

        // *** End programmer edit section *** (ИтОтчПоЛет.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ИтОтчПоЛет.Дата Get start)

                // *** End programmer edit section *** (ИтОтчПоЛет.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ИтОтчПоЛет.Дата Get end)

                // *** End programmer edit section *** (ИтОтчПоЛет.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИтОтчПоЛет.Дата Set start)

                // *** End programmer edit section *** (ИтОтчПоЛет.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ИтОтчПоЛет.Дата Set end)

                // *** End programmer edit section *** (ИтОтчПоЛет.Дата Set end)
            }
        }
        
        /// <summary>
        /// Место.
        /// </summary>
        // *** Start programmer edit section *** (ИтОтчПоЛет.Место CustomAttributes)

        // *** End programmer edit section *** (ИтОтчПоЛет.Место CustomAttributes)
        [StrLen(255)]
        public virtual string Место
        {
            get
            {
                // *** Start programmer edit section *** (ИтОтчПоЛет.Место Get start)

                // *** End programmer edit section *** (ИтОтчПоЛет.Место Get start)
                string result = this.fМесто;
                // *** Start programmer edit section *** (ИтОтчПоЛет.Место Get end)

                // *** End programmer edit section *** (ИтОтчПоЛет.Место Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИтОтчПоЛет.Место Set start)

                // *** End programmer edit section *** (ИтОтчПоЛет.Место Set start)
                this.fМесто = value;
                // *** Start programmer edit section *** (ИтОтчПоЛет.Место Set end)

                // *** End programmer edit section *** (ИтОтчПоЛет.Место Set end)
            }
        }
        
        /// <summary>
        /// ПериодДо.
        /// </summary>
        // *** Start programmer edit section *** (ИтОтчПоЛет.ПериодДо CustomAttributes)

        // *** End programmer edit section *** (ИтОтчПоЛет.ПериодДо CustomAttributes)
        public virtual System.DateTime ПериодДо
        {
            get
            {
                // *** Start programmer edit section *** (ИтОтчПоЛет.ПериодДо Get start)

                // *** End programmer edit section *** (ИтОтчПоЛет.ПериодДо Get start)
                System.DateTime result = this.fПериодДо;
                // *** Start programmer edit section *** (ИтОтчПоЛет.ПериодДо Get end)

                // *** End programmer edit section *** (ИтОтчПоЛет.ПериодДо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИтОтчПоЛет.ПериодДо Set start)

                // *** End programmer edit section *** (ИтОтчПоЛет.ПериодДо Set start)
                this.fПериодДо = value;
                // *** Start programmer edit section *** (ИтОтчПоЛет.ПериодДо Set end)

                // *** End programmer edit section *** (ИтОтчПоЛет.ПериодДо Set end)
            }
        }
        
        /// <summary>
        /// ПериодОт.
        /// </summary>
        // *** Start programmer edit section *** (ИтОтчПоЛет.ПериодОт CustomAttributes)

        // *** End programmer edit section *** (ИтОтчПоЛет.ПериодОт CustomAttributes)
        public virtual System.DateTime ПериодОт
        {
            get
            {
                // *** Start programmer edit section *** (ИтОтчПоЛет.ПериодОт Get start)

                // *** End programmer edit section *** (ИтОтчПоЛет.ПериодОт Get start)
                System.DateTime result = this.fПериодОт;
                // *** Start programmer edit section *** (ИтОтчПоЛет.ПериодОт Get end)

                // *** End programmer edit section *** (ИтОтчПоЛет.ПериодОт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИтОтчПоЛет.ПериодОт Set start)

                // *** End programmer edit section *** (ИтОтчПоЛет.ПериодОт Set start)
                this.fПериодОт = value;
                // *** Start programmer edit section *** (ИтОтчПоЛет.ПериодОт Set end)

                // *** End programmer edit section *** (ИтОтчПоЛет.ПериодОт Set end)
            }
        }
        
        /// <summary>
        /// Ит отч по лет.
        /// </summary>
        // *** Start programmer edit section *** (ИтОтчПоЛет.СпрСотр CustomAttributes)

        // *** End programmer edit section *** (ИтОтчПоЛет.СпрСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСотр"})]
        [NotNull()]
        public virtual IIS.Laboratornaya_rabota_Stacionar_2.СпрСотр СпрСотр
        {
            get
            {
                // *** Start programmer edit section *** (ИтОтчПоЛет.СпрСотр Get start)

                // *** End programmer edit section *** (ИтОтчПоЛет.СпрСотр Get start)
                IIS.Laboratornaya_rabota_Stacionar_2.СпрСотр result = this.fСпрСотр;
                // *** Start programmer edit section *** (ИтОтчПоЛет.СпрСотр Get end)

                // *** End programmer edit section *** (ИтОтчПоЛет.СпрСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИтОтчПоЛет.СпрСотр Set start)

                // *** End programmer edit section *** (ИтОтчПоЛет.СпрСотр Set start)
                this.fСпрСотр = value;
                // *** Start programmer edit section *** (ИтОтчПоЛет.СпрСотр Set end)

                // *** End programmer edit section *** (ИтОтчПоЛет.СпрСотр Set end)
            }
        }
        
        /// <summary>
        /// Ит отч по лет.
        /// </summary>
        // *** Start programmer edit section *** (ИтОтчПоЛет.ТЧИтОтчПоЛет CustomAttributes)

        // *** End programmer edit section *** (ИтОтчПоЛет.ТЧИтОтчПоЛет CustomAttributes)
        public virtual IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТЧИтОтчПоЛет ТЧИтОтчПоЛет
        {
            get
            {
                // *** Start programmer edit section *** (ИтОтчПоЛет.ТЧИтОтчПоЛет Get start)

                // *** End programmer edit section *** (ИтОтчПоЛет.ТЧИтОтчПоЛет Get start)
                if ((this.fТЧИтОтчПоЛет == null))
                {
                    this.fТЧИтОтчПоЛет = new IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТЧИтОтчПоЛет(this);
                }
                IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТЧИтОтчПоЛет result = this.fТЧИтОтчПоЛет;
                // *** Start programmer edit section *** (ИтОтчПоЛет.ТЧИтОтчПоЛет Get end)

                // *** End programmer edit section *** (ИтОтчПоЛет.ТЧИтОтчПоЛет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИтОтчПоЛет.ТЧИтОтчПоЛет Set start)

                // *** End programmer edit section *** (ИтОтчПоЛет.ТЧИтОтчПоЛет Set start)
                this.fТЧИтОтчПоЛет = value;
                // *** Start programmer edit section *** (ИтОтчПоЛет.ТЧИтОтчПоЛет Set end)

                // *** End programmer edit section *** (ИтОтчПоЛет.ТЧИтОтчПоЛет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИтОтчПоЛетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИтОтчПоЛетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИтОтчПоЛетE", typeof(IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоЛет));
                }
            }
            
            /// <summary>
            /// "ИтОтчПоЛетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИтОтчПоЛетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИтОтчПоЛетL", typeof(IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоЛет));
                }
            }
        }
    }
}
