//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laboratornaya_rabota_Stacionar_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ит отч по бол.
    /// </summary>
    // *** Start programmer edit section *** (ИтОтчПоБол CustomAttributes)

    // *** End programmer edit section *** (ИтОтчПоБол CustomAttributes)
    [AutoAltered()]
    [Caption("Ит отч по бол")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИтОтчПоБолE", new string[] {
            "Дата as \'Дата создания\'",
            "СпрСотр as \'Фио сотрудника\'",
            "СпрСотр.Фио as \'Фио сотрудника\'",
            "ПериодОт as \'ПериодОт\'",
            "ПериодДо as \'ПериодДо\'"})]
    [AssociatedDetailViewAttribute("ИтОтчПоБолE", "ТчИтОтчПоБол", "ТчИтОтчПоБолE", true, "", "Табличная часть итоговый отчет по больным стационара", true, new string[] {
            ""})]
    [View("ИтОтчПоБолL", new string[] {
            "СпрСотр.Фио as \'Фио сотрудника\'",
            "Дата as \'Дата создания\'",
            "ПериодОт as \'Период От\'",
            "ПериодДо as \'Период До\'"})]
    public class ИтОтчПоБол : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private System.DateTime fПериодОт;
        
        private System.DateTime fПериодДо;
        
        private IIS.Laboratornaya_rabota_Stacionar_2.СпрСотр fСпрСотр;
        
        private IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТчИтОтчПоБол fТчИтОтчПоБол;
        
        // *** Start programmer edit section *** (ИтОтчПоБол CustomMembers)

        // *** End programmer edit section *** (ИтОтчПоБол CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ИтОтчПоБол.Дата CustomAttributes)

        // *** End programmer edit section *** (ИтОтчПоБол.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ИтОтчПоБол.Дата Get start)

                // *** End programmer edit section *** (ИтОтчПоБол.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ИтОтчПоБол.Дата Get end)

                // *** End programmer edit section *** (ИтОтчПоБол.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИтОтчПоБол.Дата Set start)

                // *** End programmer edit section *** (ИтОтчПоБол.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ИтОтчПоБол.Дата Set end)

                // *** End programmer edit section *** (ИтОтчПоБол.Дата Set end)
            }
        }
        
        /// <summary>
        /// ПериодДо.
        /// </summary>
        // *** Start programmer edit section *** (ИтОтчПоБол.ПериодДо CustomAttributes)

        // *** End programmer edit section *** (ИтОтчПоБол.ПериодДо CustomAttributes)
        public virtual System.DateTime ПериодДо
        {
            get
            {
                // *** Start programmer edit section *** (ИтОтчПоБол.ПериодДо Get start)

                // *** End programmer edit section *** (ИтОтчПоБол.ПериодДо Get start)
                System.DateTime result = this.fПериодДо;
                // *** Start programmer edit section *** (ИтОтчПоБол.ПериодДо Get end)

                // *** End programmer edit section *** (ИтОтчПоБол.ПериодДо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИтОтчПоБол.ПериодДо Set start)

                // *** End programmer edit section *** (ИтОтчПоБол.ПериодДо Set start)
                this.fПериодДо = value;
                // *** Start programmer edit section *** (ИтОтчПоБол.ПериодДо Set end)

                // *** End programmer edit section *** (ИтОтчПоБол.ПериодДо Set end)
            }
        }
        
        /// <summary>
        /// ПериодОт.
        /// </summary>
        // *** Start programmer edit section *** (ИтОтчПоБол.ПериодОт CustomAttributes)

        // *** End programmer edit section *** (ИтОтчПоБол.ПериодОт CustomAttributes)
        public virtual System.DateTime ПериодОт
        {
            get
            {
                // *** Start programmer edit section *** (ИтОтчПоБол.ПериодОт Get start)

                // *** End programmer edit section *** (ИтОтчПоБол.ПериодОт Get start)
                System.DateTime result = this.fПериодОт;
                // *** Start programmer edit section *** (ИтОтчПоБол.ПериодОт Get end)

                // *** End programmer edit section *** (ИтОтчПоБол.ПериодОт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИтОтчПоБол.ПериодОт Set start)

                // *** End programmer edit section *** (ИтОтчПоБол.ПериодОт Set start)
                this.fПериодОт = value;
                // *** Start programmer edit section *** (ИтОтчПоБол.ПериодОт Set end)

                // *** End programmer edit section *** (ИтОтчПоБол.ПериодОт Set end)
            }
        }
        
        /// <summary>
        /// Ит отч по бол.
        /// </summary>
        // *** Start programmer edit section *** (ИтОтчПоБол.СпрСотр CustomAttributes)

        // *** End programmer edit section *** (ИтОтчПоБол.СпрСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСотр"})]
        [NotNull()]
        public virtual IIS.Laboratornaya_rabota_Stacionar_2.СпрСотр СпрСотр
        {
            get
            {
                // *** Start programmer edit section *** (ИтОтчПоБол.СпрСотр Get start)

                // *** End programmer edit section *** (ИтОтчПоБол.СпрСотр Get start)
                IIS.Laboratornaya_rabota_Stacionar_2.СпрСотр result = this.fСпрСотр;
                // *** Start programmer edit section *** (ИтОтчПоБол.СпрСотр Get end)

                // *** End programmer edit section *** (ИтОтчПоБол.СпрСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИтОтчПоБол.СпрСотр Set start)

                // *** End programmer edit section *** (ИтОтчПоБол.СпрСотр Set start)
                this.fСпрСотр = value;
                // *** Start programmer edit section *** (ИтОтчПоБол.СпрСотр Set end)

                // *** End programmer edit section *** (ИтОтчПоБол.СпрСотр Set end)
            }
        }
        
        /// <summary>
        /// Ит отч по бол.
        /// </summary>
        // *** Start programmer edit section *** (ИтОтчПоБол.ТчИтОтчПоБол CustomAttributes)

        // *** End programmer edit section *** (ИтОтчПоБол.ТчИтОтчПоБол CustomAttributes)
        public virtual IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТчИтОтчПоБол ТчИтОтчПоБол
        {
            get
            {
                // *** Start programmer edit section *** (ИтОтчПоБол.ТчИтОтчПоБол Get start)

                // *** End programmer edit section *** (ИтОтчПоБол.ТчИтОтчПоБол Get start)
                if ((this.fТчИтОтчПоБол == null))
                {
                    this.fТчИтОтчПоБол = new IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТчИтОтчПоБол(this);
                }
                IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТчИтОтчПоБол result = this.fТчИтОтчПоБол;
                // *** Start programmer edit section *** (ИтОтчПоБол.ТчИтОтчПоБол Get end)

                // *** End programmer edit section *** (ИтОтчПоБол.ТчИтОтчПоБол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИтОтчПоБол.ТчИтОтчПоБол Set start)

                // *** End programmer edit section *** (ИтОтчПоБол.ТчИтОтчПоБол Set start)
                this.fТчИтОтчПоБол = value;
                // *** Start programmer edit section *** (ИтОтчПоБол.ТчИтОтчПоБол Set end)

                // *** End programmer edit section *** (ИтОтчПоБол.ТчИтОтчПоБол Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИтОтчПоБолE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИтОтчПоБолE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИтОтчПоБолE", typeof(IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоБол));
                }
            }
            
            /// <summary>
            /// "ИтОтчПоБолL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИтОтчПоБолL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИтОтчПоБолL", typeof(IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоБол));
                }
            }
        }
    }
}
