//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laboratornaya_rabota_Stacionar_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пациент.
    /// </summary>
    // *** Start programmer edit section *** (Пациент CustomAttributes)

    // *** End programmer edit section *** (Пациент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПациентE", new string[] {
            "Фио as \'Фио\'"})]
    [View("ПациентL", new string[] {
            "Фио as \'Фио\'"})]
    public class Пациент : ICSSoft.STORMNET.DataObject
    {
        
        private string fФио;
        
        // *** Start programmer edit section *** (Пациент CustomMembers)

        // *** End programmer edit section *** (Пациент CustomMembers)

        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (Пациент.Фио CustomAttributes)

        // *** End programmer edit section *** (Пациент.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (Пациент.Фио Get start)

                // *** End programmer edit section *** (Пациент.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (Пациент.Фио Get end)

                // *** End programmer edit section *** (Пациент.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пациент.Фио Set start)

                // *** End programmer edit section *** (Пациент.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (Пациент.Фио Set end)

                // *** End programmer edit section *** (Пациент.Фио Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПациентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПациентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПациентE", typeof(IIS.Laboratornaya_rabota_Stacionar_2.Пациент));
                }
            }
            
            /// <summary>
            /// "ПациентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПациентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПациентL", typeof(IIS.Laboratornaya_rabota_Stacionar_2.Пациент));
                }
            }
        }
    }
}
