//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laboratornaya_rabota_Stacionar_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спр сотр.
    /// </summary>
    // *** Start programmer edit section *** (СпрСотр CustomAttributes)

    // *** End programmer edit section *** (СпрСотр CustomAttributes)
    [AutoAltered()]
    [Caption("Спр сотр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрСотрE", new string[] {
            "Фио as \'Фио сотрудника\'",
            "Должность as \'Должность\'",
            "Должность.Наименование as \'Должность\'"})]
    [View("СпрСотрL", new string[] {
            "Фио as \'Фио сотрудника\'",
            "Должность.Наименование as \'Должность\'"})]
    public class СпрСотр : ICSSoft.STORMNET.DataObject
    {
        
        private string fФио;
        
        private IIS.Laboratornaya_rabota_Stacionar_2.Должность fДолжность;
        
        // *** Start programmer edit section *** (СпрСотр CustomMembers)

        // *** End programmer edit section *** (СпрСотр CustomMembers)

        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (СпрСотр.Фио CustomAttributes)

        // *** End programmer edit section *** (СпрСотр.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (СпрСотр.Фио Get start)

                // *** End programmer edit section *** (СпрСотр.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (СпрСотр.Фио Get end)

                // *** End programmer edit section *** (СпрСотр.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрСотр.Фио Set start)

                // *** End programmer edit section *** (СпрСотр.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (СпрСотр.Фио Set end)

                // *** End programmer edit section *** (СпрСотр.Фио Set end)
            }
        }
        
        /// <summary>
        /// Спр сотр.
        /// </summary>
        // *** Start programmer edit section *** (СпрСотр.Должность CustomAttributes)

        // *** End programmer edit section *** (СпрСотр.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.Laboratornaya_rabota_Stacionar_2.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (СпрСотр.Должность Get start)

                // *** End programmer edit section *** (СпрСотр.Должность Get start)
                IIS.Laboratornaya_rabota_Stacionar_2.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (СпрСотр.Должность Get end)

                // *** End programmer edit section *** (СпрСотр.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрСотр.Должность Set start)

                // *** End programmer edit section *** (СпрСотр.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (СпрСотр.Должность Set end)

                // *** End programmer edit section *** (СпрСотр.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрСотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрСотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрСотрE", typeof(IIS.Laboratornaya_rabota_Stacionar_2.СпрСотр));
                }
            }
            
            /// <summary>
            /// "СпрСотрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрСотрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрСотрL", typeof(IIS.Laboratornaya_rabota_Stacionar_2.СпрСотр));
                }
            }
        }
    }
}
