//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laboratornaya_rabota_Stacionar_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч отч леч пац.
    /// </summary>
    // *** Start programmer edit section *** (ТчОтчЛечПац CustomAttributes)

    // *** End programmer edit section *** (ТчОтчЛечПац CustomAttributes)
    [AutoAltered()]
    [Caption("Тч отч леч пац")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчОтчЛечПацE", new string[] {
            "Диагноз as \'Диагноз\'",
            "Диагноз.Наименование as \'Диагноз\'",
            "ОцЛеч as \'Оценка лечения\'",
            "Рецептура as \'Рецептура\'"})]
    [MasterViewDefineAttribute("ТчОтчЛечПацE", "Диагноз", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Диагноз")]
    public class ТчОтчЛечПац : ICSSoft.STORMNET.DataObject
    {
        
        private string fОцЛеч;
        
        private string fРецептура;
        
        private IIS.Laboratornaya_rabota_Stacionar_2.Диагноз fДиагноз;
        
        private IIS.Laboratornaya_rabota_Stacionar_2.ОтПоОцЛечПац fОтПоОцЛечПац;
        
        // *** Start programmer edit section *** (ТчОтчЛечПац CustomMembers)

        // *** End programmer edit section *** (ТчОтчЛечПац CustomMembers)

        
        /// <summary>
        /// ОцЛеч.
        /// </summary>
        // *** Start programmer edit section *** (ТчОтчЛечПац.ОцЛеч CustomAttributes)

        // *** End programmer edit section *** (ТчОтчЛечПац.ОцЛеч CustomAttributes)
        [StrLen(255)]
        public virtual string ОцЛеч
        {
            get
            {
                // *** Start programmer edit section *** (ТчОтчЛечПац.ОцЛеч Get start)

                // *** End programmer edit section *** (ТчОтчЛечПац.ОцЛеч Get start)
                string result = this.fОцЛеч;
                // *** Start programmer edit section *** (ТчОтчЛечПац.ОцЛеч Get end)

                // *** End programmer edit section *** (ТчОтчЛечПац.ОцЛеч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОтчЛечПац.ОцЛеч Set start)

                // *** End programmer edit section *** (ТчОтчЛечПац.ОцЛеч Set start)
                this.fОцЛеч = value;
                // *** Start programmer edit section *** (ТчОтчЛечПац.ОцЛеч Set end)

                // *** End programmer edit section *** (ТчОтчЛечПац.ОцЛеч Set end)
            }
        }
        
        /// <summary>
        /// Рецептура.
        /// </summary>
        // *** Start programmer edit section *** (ТчОтчЛечПац.Рецептура CustomAttributes)

        // *** End programmer edit section *** (ТчОтчЛечПац.Рецептура CustomAttributes)
        [StrLen(255)]
        public virtual string Рецептура
        {
            get
            {
                // *** Start programmer edit section *** (ТчОтчЛечПац.Рецептура Get start)

                // *** End programmer edit section *** (ТчОтчЛечПац.Рецептура Get start)
                string result = this.fРецептура;
                // *** Start programmer edit section *** (ТчОтчЛечПац.Рецептура Get end)

                // *** End programmer edit section *** (ТчОтчЛечПац.Рецептура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОтчЛечПац.Рецептура Set start)

                // *** End programmer edit section *** (ТчОтчЛечПац.Рецептура Set start)
                this.fРецептура = value;
                // *** Start programmer edit section *** (ТчОтчЛечПац.Рецептура Set end)

                // *** End programmer edit section *** (ТчОтчЛечПац.Рецептура Set end)
            }
        }
        
        /// <summary>
        /// Тч отч леч пац.
        /// </summary>
        // *** Start programmer edit section *** (ТчОтчЛечПац.Диагноз CustomAttributes)

        // *** End programmer edit section *** (ТчОтчЛечПац.Диагноз CustomAttributes)
        [PropertyStorage(new string[] {
                "Диагноз"})]
        [NotNull()]
        public virtual IIS.Laboratornaya_rabota_Stacionar_2.Диагноз Диагноз
        {
            get
            {
                // *** Start programmer edit section *** (ТчОтчЛечПац.Диагноз Get start)

                // *** End programmer edit section *** (ТчОтчЛечПац.Диагноз Get start)
                IIS.Laboratornaya_rabota_Stacionar_2.Диагноз result = this.fДиагноз;
                // *** Start programmer edit section *** (ТчОтчЛечПац.Диагноз Get end)

                // *** End programmer edit section *** (ТчОтчЛечПац.Диагноз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОтчЛечПац.Диагноз Set start)

                // *** End programmer edit section *** (ТчОтчЛечПац.Диагноз Set start)
                this.fДиагноз = value;
                // *** Start programmer edit section *** (ТчОтчЛечПац.Диагноз Set end)

                // *** End programmer edit section *** (ТчОтчЛечПац.Диагноз Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Laboratornaya_rabota_Stacionar_2.ОтПоОцЛечПац.
        /// </summary>
        // *** Start programmer edit section *** (ТчОтчЛечПац.ОтПоОцЛечПац CustomAttributes)

        // *** End programmer edit section *** (ТчОтчЛечПац.ОтПоОцЛечПац CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ОтПоОцЛечПац"})]
        public virtual IIS.Laboratornaya_rabota_Stacionar_2.ОтПоОцЛечПац ОтПоОцЛечПац
        {
            get
            {
                // *** Start programmer edit section *** (ТчОтчЛечПац.ОтПоОцЛечПац Get start)

                // *** End programmer edit section *** (ТчОтчЛечПац.ОтПоОцЛечПац Get start)
                IIS.Laboratornaya_rabota_Stacionar_2.ОтПоОцЛечПац result = this.fОтПоОцЛечПац;
                // *** Start programmer edit section *** (ТчОтчЛечПац.ОтПоОцЛечПац Get end)

                // *** End programmer edit section *** (ТчОтчЛечПац.ОтПоОцЛечПац Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОтчЛечПац.ОтПоОцЛечПац Set start)

                // *** End programmer edit section *** (ТчОтчЛечПац.ОтПоОцЛечПац Set start)
                this.fОтПоОцЛечПац = value;
                // *** Start programmer edit section *** (ТчОтчЛечПац.ОтПоОцЛечПац Set end)

                // *** End programmer edit section *** (ТчОтчЛечПац.ОтПоОцЛечПац Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчОтчЛечПацE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчОтчЛечПацE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчОтчЛечПацE", typeof(IIS.Laboratornaya_rabota_Stacionar_2.ТчОтчЛечПац));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТчОтчЛечПац.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТчОтчЛечПац CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТчОтчЛечПац CustomAttributes)
    public class DetailArrayOfТчОтчЛечПац : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТчОтчЛечПац members)

        // *** End programmer edit section *** (IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТчОтчЛечПац members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТчОтчЛечПац by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТчОтчЛечПац.
        /// </summary>
        public DetailArrayOfТчОтчЛечПац(IIS.Laboratornaya_rabota_Stacionar_2.ОтПоОцЛечПац fОтПоОцЛечПац) : 
                base(typeof(ТчОтчЛечПац), ((ICSSoft.STORMNET.DataObject)(fОтПоОцЛечПац)))
        {
        }
        
        public IIS.Laboratornaya_rabota_Stacionar_2.ТчОтчЛечПац this[int index]
        {
            get
            {
                return ((IIS.Laboratornaya_rabota_Stacionar_2.ТчОтчЛечПац)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Laboratornaya_rabota_Stacionar_2.ТчОтчЛечПац dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
