//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laboratornaya_rabota_Stacionar_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч ит отч по бол.
    /// </summary>
    // *** Start programmer edit section *** (ТчИтОтчПоБол CustomAttributes)

    // *** End programmer edit section *** (ТчИтОтчПоБол CustomAttributes)
    [AutoAltered()]
    [Caption("Тч ит отч по бол")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчИтОтчПоБолE", new string[] {
            "ЛеПоПлан as \'Лечение по плану\'",
            "ЛечПоФакт as \'Лечению по факту\'",
            "Показатель as \'Показатель\'"})]
    public class ТчИтОтчПоБол : ICSSoft.STORMNET.DataObject
    {
        
        private string fЛечПоФакт;
        
        private string fЛеПоПлан;
        
        private string fПоказатель;
        
        private IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоБол fИтОтчПоБол;
        
        // *** Start programmer edit section *** (ТчИтОтчПоБол CustomMembers)

        // *** End programmer edit section *** (ТчИтОтчПоБол CustomMembers)

        
        /// <summary>
        /// ЛеПоПлан.
        /// </summary>
        // *** Start programmer edit section *** (ТчИтОтчПоБол.ЛеПоПлан CustomAttributes)

        // *** End programmer edit section *** (ТчИтОтчПоБол.ЛеПоПлан CustomAttributes)
        [StrLen(255)]
        public virtual string ЛеПоПлан
        {
            get
            {
                // *** Start programmer edit section *** (ТчИтОтчПоБол.ЛеПоПлан Get start)

                // *** End programmer edit section *** (ТчИтОтчПоБол.ЛеПоПлан Get start)
                string result = this.fЛеПоПлан;
                // *** Start programmer edit section *** (ТчИтОтчПоБол.ЛеПоПлан Get end)

                // *** End programmer edit section *** (ТчИтОтчПоБол.ЛеПоПлан Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчИтОтчПоБол.ЛеПоПлан Set start)

                // *** End programmer edit section *** (ТчИтОтчПоБол.ЛеПоПлан Set start)
                this.fЛеПоПлан = value;
                // *** Start programmer edit section *** (ТчИтОтчПоБол.ЛеПоПлан Set end)

                // *** End programmer edit section *** (ТчИтОтчПоБол.ЛеПоПлан Set end)
            }
        }
        
        /// <summary>
        /// ЛечПоФакт.
        /// </summary>
        // *** Start programmer edit section *** (ТчИтОтчПоБол.ЛечПоФакт CustomAttributes)

        // *** End programmer edit section *** (ТчИтОтчПоБол.ЛечПоФакт CustomAttributes)
        [StrLen(255)]
        public virtual string ЛечПоФакт
        {
            get
            {
                // *** Start programmer edit section *** (ТчИтОтчПоБол.ЛечПоФакт Get start)

                // *** End programmer edit section *** (ТчИтОтчПоБол.ЛечПоФакт Get start)
                string result = this.fЛечПоФакт;
                // *** Start programmer edit section *** (ТчИтОтчПоБол.ЛечПоФакт Get end)

                // *** End programmer edit section *** (ТчИтОтчПоБол.ЛечПоФакт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчИтОтчПоБол.ЛечПоФакт Set start)

                // *** End programmer edit section *** (ТчИтОтчПоБол.ЛечПоФакт Set start)
                this.fЛечПоФакт = value;
                // *** Start programmer edit section *** (ТчИтОтчПоБол.ЛечПоФакт Set end)

                // *** End programmer edit section *** (ТчИтОтчПоБол.ЛечПоФакт Set end)
            }
        }
        
        /// <summary>
        /// Показатель.
        /// </summary>
        // *** Start programmer edit section *** (ТчИтОтчПоБол.Показатель CustomAttributes)

        // *** End programmer edit section *** (ТчИтОтчПоБол.Показатель CustomAttributes)
        [StrLen(255)]
        public virtual string Показатель
        {
            get
            {
                // *** Start programmer edit section *** (ТчИтОтчПоБол.Показатель Get start)

                // *** End programmer edit section *** (ТчИтОтчПоБол.Показатель Get start)
                string result = this.fПоказатель;
                // *** Start programmer edit section *** (ТчИтОтчПоБол.Показатель Get end)

                // *** End programmer edit section *** (ТчИтОтчПоБол.Показатель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчИтОтчПоБол.Показатель Set start)

                // *** End programmer edit section *** (ТчИтОтчПоБол.Показатель Set start)
                this.fПоказатель = value;
                // *** Start programmer edit section *** (ТчИтОтчПоБол.Показатель Set end)

                // *** End programmer edit section *** (ТчИтОтчПоБол.Показатель Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоБол.
        /// </summary>
        // *** Start programmer edit section *** (ТчИтОтчПоБол.ИтОтчПоБол CustomAttributes)

        // *** End programmer edit section *** (ТчИтОтчПоБол.ИтОтчПоБол CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ИтОтчПоБол"})]
        public virtual IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоБол ИтОтчПоБол
        {
            get
            {
                // *** Start programmer edit section *** (ТчИтОтчПоБол.ИтОтчПоБол Get start)

                // *** End programmer edit section *** (ТчИтОтчПоБол.ИтОтчПоБол Get start)
                IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоБол result = this.fИтОтчПоБол;
                // *** Start programmer edit section *** (ТчИтОтчПоБол.ИтОтчПоБол Get end)

                // *** End programmer edit section *** (ТчИтОтчПоБол.ИтОтчПоБол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчИтОтчПоБол.ИтОтчПоБол Set start)

                // *** End programmer edit section *** (ТчИтОтчПоБол.ИтОтчПоБол Set start)
                this.fИтОтчПоБол = value;
                // *** Start programmer edit section *** (ТчИтОтчПоБол.ИтОтчПоБол Set end)

                // *** End programmer edit section *** (ТчИтОтчПоБол.ИтОтчПоБол Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчИтОтчПоБолE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчИтОтчПоБолE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчИтОтчПоБолE", typeof(IIS.Laboratornaya_rabota_Stacionar_2.ТчИтОтчПоБол));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТчИтОтчПоБол.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТчИтОтчПоБол CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТчИтОтчПоБол CustomAttributes)
    public class DetailArrayOfТчИтОтчПоБол : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТчИтОтчПоБол members)

        // *** End programmer edit section *** (IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТчИтОтчПоБол members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТчИтОтчПоБол by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТчИтОтчПоБол.
        /// </summary>
        public DetailArrayOfТчИтОтчПоБол(IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоБол fИтОтчПоБол) : 
                base(typeof(ТчИтОтчПоБол), ((ICSSoft.STORMNET.DataObject)(fИтОтчПоБол)))
        {
        }
        
        public IIS.Laboratornaya_rabota_Stacionar_2.ТчИтОтчПоБол this[int index]
        {
            get
            {
                return ((IIS.Laboratornaya_rabota_Stacionar_2.ТчИтОтчПоБол)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Laboratornaya_rabota_Stacionar_2.ТчИтОтчПоБол dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
