//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laboratornaya_rabota_Stacionar_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч ит отч по лет.
    /// </summary>
    // *** Start programmer edit section *** (ТЧИтОтчПоЛет CustomAttributes)

    // *** End programmer edit section *** (ТЧИтОтчПоЛет CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч ит отч по лет")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧИтОтчПоЛетE", new string[] {
            "ПричЛет as \'Причина летальности\'",
            "Число as \'Число людей\'"})]
    public class ТЧИтОтчПоЛет : ICSSoft.STORMNET.DataObject
    {
        
        private string fПричЛет;
        
        private string fЧисло;
        
        private IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоЛет fИтОтчПоЛет;
        
        // *** Start programmer edit section *** (ТЧИтОтчПоЛет CustomMembers)

        // *** End programmer edit section *** (ТЧИтОтчПоЛет CustomMembers)

        
        /// <summary>
        /// ПричЛет.
        /// </summary>
        // *** Start programmer edit section *** (ТЧИтОтчПоЛет.ПричЛет CustomAttributes)

        // *** End programmer edit section *** (ТЧИтОтчПоЛет.ПричЛет CustomAttributes)
        [StrLen(255)]
        public virtual string ПричЛет
        {
            get
            {
                // *** Start programmer edit section *** (ТЧИтОтчПоЛет.ПричЛет Get start)

                // *** End programmer edit section *** (ТЧИтОтчПоЛет.ПричЛет Get start)
                string result = this.fПричЛет;
                // *** Start programmer edit section *** (ТЧИтОтчПоЛет.ПричЛет Get end)

                // *** End programmer edit section *** (ТЧИтОтчПоЛет.ПричЛет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧИтОтчПоЛет.ПричЛет Set start)

                // *** End programmer edit section *** (ТЧИтОтчПоЛет.ПричЛет Set start)
                this.fПричЛет = value;
                // *** Start programmer edit section *** (ТЧИтОтчПоЛет.ПричЛет Set end)

                // *** End programmer edit section *** (ТЧИтОтчПоЛет.ПричЛет Set end)
            }
        }
        
        /// <summary>
        /// Число.
        /// </summary>
        // *** Start programmer edit section *** (ТЧИтОтчПоЛет.Число CustomAttributes)

        // *** End programmer edit section *** (ТЧИтОтчПоЛет.Число CustomAttributes)
        [StrLen(255)]
        public virtual string Число
        {
            get
            {
                // *** Start programmer edit section *** (ТЧИтОтчПоЛет.Число Get start)

                // *** End programmer edit section *** (ТЧИтОтчПоЛет.Число Get start)
                string result = this.fЧисло;
                // *** Start programmer edit section *** (ТЧИтОтчПоЛет.Число Get end)

                // *** End programmer edit section *** (ТЧИтОтчПоЛет.Число Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧИтОтчПоЛет.Число Set start)

                // *** End programmer edit section *** (ТЧИтОтчПоЛет.Число Set start)
                this.fЧисло = value;
                // *** Start programmer edit section *** (ТЧИтОтчПоЛет.Число Set end)

                // *** End programmer edit section *** (ТЧИтОтчПоЛет.Число Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоЛет.
        /// </summary>
        // *** Start programmer edit section *** (ТЧИтОтчПоЛет.ИтОтчПоЛет CustomAttributes)

        // *** End programmer edit section *** (ТЧИтОтчПоЛет.ИтОтчПоЛет CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ИтОтчПоЛет"})]
        public virtual IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоЛет ИтОтчПоЛет
        {
            get
            {
                // *** Start programmer edit section *** (ТЧИтОтчПоЛет.ИтОтчПоЛет Get start)

                // *** End programmer edit section *** (ТЧИтОтчПоЛет.ИтОтчПоЛет Get start)
                IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоЛет result = this.fИтОтчПоЛет;
                // *** Start programmer edit section *** (ТЧИтОтчПоЛет.ИтОтчПоЛет Get end)

                // *** End programmer edit section *** (ТЧИтОтчПоЛет.ИтОтчПоЛет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧИтОтчПоЛет.ИтОтчПоЛет Set start)

                // *** End programmer edit section *** (ТЧИтОтчПоЛет.ИтОтчПоЛет Set start)
                this.fИтОтчПоЛет = value;
                // *** Start programmer edit section *** (ТЧИтОтчПоЛет.ИтОтчПоЛет Set end)

                // *** End programmer edit section *** (ТЧИтОтчПоЛет.ИтОтчПоЛет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧИтОтчПоЛетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧИтОтчПоЛетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧИтОтчПоЛетE", typeof(IIS.Laboratornaya_rabota_Stacionar_2.ТЧИтОтчПоЛет));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧИтОтчПоЛет.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧИтОтчПоЛет CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧИтОтчПоЛет CustomAttributes)
    public class DetailArrayOfТЧИтОтчПоЛет : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТЧИтОтчПоЛет members)

        // *** End programmer edit section *** (IIS.Laboratornaya_rabota_Stacionar_2.DetailArrayOfТЧИтОтчПоЛет members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧИтОтчПоЛет by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧИтОтчПоЛет.
        /// </summary>
        public DetailArrayOfТЧИтОтчПоЛет(IIS.Laboratornaya_rabota_Stacionar_2.ИтОтчПоЛет fИтОтчПоЛет) : 
                base(typeof(ТЧИтОтчПоЛет), ((ICSSoft.STORMNET.DataObject)(fИтОтчПоЛет)))
        {
        }
        
        public IIS.Laboratornaya_rabota_Stacionar_2.ТЧИтОтчПоЛет this[int index]
        {
            get
            {
                return ((IIS.Laboratornaya_rabota_Stacionar_2.ТЧИтОтчПоЛет)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Laboratornaya_rabota_Stacionar_2.ТЧИтОтчПоЛет dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
